# 10/29/2023 Designed by Honatzin
# Create MQ Server

version: "3.9"
services:
  mqseries:
    hostname: ibm-mq
    container_name: ibm-mq
    image: icr.io/ibm-messaging/mq:9.3.2.0-r1
    ports:
      - "1414:1414"
      - "9443:9443"
      - "9157:9157"
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
      - TZ=America/New_York
      - MQ_ENABLE_METRICS=true 
      - MQ_DEV=false
      - MQ_ADMIN_PASSWORD=manage
    volumes:
      -  ./20-config.mqsc:/etc/mqm/20-config.mqsc # Volume to store wM databases 


volumes: 
  mqvolume:

networks:
  mq-default:
